language: python
python: 3.6

cache:
  pip: true

stages:
  - test
  - name: deploy
    if: type != pull_request

env:
  global:
    - ENCRYPTION_LABEL: "defac9b1fa56"
    - COMMIT_AUTHOR_EMAIL: "nobody@coala.io"

jobs:
  include:
    # This more closely emulates a forked build
    # However the git remote is not correct
    # Only a GH_TOKEN is required.
    - stage: test
      env: GL_TOKEN="" GCI_TOKEN="" OH_TOKEN=""
    # A proper build with the tokens available
    - stage: deploy
      after_success: ./.ci/deploy.sh

before_install:
  - printf '%s\n'
           "$(cat test-requirements.txt requirements.txt)"
           > requirements.txt

script:
  - ./.ci/build.sh
  - rm -rf private/

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
